#+title: peek.el
#+author: Naoya Yamashita

[[https://github.com/conao3/peek.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/peek.el.svg?style=flat-square]]
[[https://github.com/conao3/peek.el/releases][https://img.shields.io/github/tag/conao3/peek.el.svg?style=flat-square]]
[[https://github.com/conao3/peek.el/actions][https://github.com/conao3/peek.el/workflows/Main%20workflow/badge.svg]]

A lightweight Emacs minor mode that displays a live preview window for grep and compilation results.

* Overview

When navigating through grep or compilation output, peek.el automatically displays a preview of the file at the current error location in an adjacent window. This provides a seamless way to browse search results without losing your place in the compilation buffer.

* Features

- Automatic preview updates as you move through grep/compilation results
- Non-intrusive design that works alongside your existing workflow
- Minimal configuration required

* Requirements

- Emacs 26.1 or later

* Installation

** Using leaf.el

#+begin_src emacs-lisp
(leaf peek
  :ensure t)
#+end_src

** Using use-package

#+begin_src emacs-lisp
(use-package peek
  :ensure t)
#+end_src

** Manual Installation

Clone this repository and add it to your load path:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/peek.el")
(require 'peek)
#+end_src

* Usage

After running a grep or compile command, enable peek-mode in the compilation buffer:

#+begin_src emacs-lisp
M-x peek-mode
#+end_src

As you navigate through the results using =n= and =p= (or any movement commands), the corresponding file location will be displayed in the peek window.

To disable the preview, run =M-x peek-mode= again to toggle it off.

** Key Bindings

You may want to add a convenient binding in compilation-mode:

#+begin_src emacs-lisp
(define-key compilation-mode-map (kbd "P") #'peek-mode)
#+end_src

* Customization

peek.el is designed to work out of the box with sensible defaults. The mode integrates with standard compilation-mode functionality.

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests on GitHub.

** Development Setup

1. Install [[https://github.com/cask/cask][Cask]] for dependency management
2. Clone the repository
3. Run =make= to set up git hooks
4. Run =make test= to verify your changes

** Submitting Changes

1. Fork the repository
2. Create a feature branch
3. Make your changes and ensure tests pass
4. Submit a pull request

* License

GPL-3.0. See [[https://github.com/conao3/peek.el/blob/master/LICENSE][LICENSE]] for details.

Copyright (c) Naoya Yamashita

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
